Budgetco/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading.Tasks;
using Budgetco.Constants;
using Budgetco.Data;
using Budgetco.Data.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Newtonsoft.Json;

namespace Budgetco.Controllers
{
    public class GroupsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IBudgetRepository _repository;

        public GroupsController(UserManager<ApplicationUser> userManager, IBudgetRepository repository)
        {
            _userManager = userManager;
            _repository = repository;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var userGroups = _repository.GetGroups(user);
            var model = new GroupsViewModel {Groups = userGroups.OrderBy(t=>t.GroupNavigation.Name).ToList()};
            foreach (var group in userGroups)
            {
                foreach (var record in group.GroupNavigation.Records)
                {
                    model.PartialModel.Add(record, group);
                }
                
            }
            return View(model);
        }

        [HttpGet]
        public async Task<string> GetGroups()
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            List<UserGroup> userGroups = _repository.GetGroups(user);
            List<string> groupNames = new List<string>();
            foreach (var group in userGroups)
            {
                groupNames.Add(group.GroupNavigation.Name);
            }

            return groupNames.Count == 0 ? null : JsonConvert.SerializeObject(groupNames);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<string> AddGroup(string name, string[] emails)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            List<string> filteredEmails = emails.ToList();
            //remove users email from list (he is automatically added to group as a creator)
            filteredEmails.RemoveAll(t => t.Equals(user.Email));
            //convert to set that removes duplicates and transform to list
            return _repository.AddGroup(name, filteredEmails.ToImmutableHashSet().ToList(), user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<string> AddUserToGroup(string name, string email)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            if (user.NormalizedEmail.Equals(email.Normalize()))
                return "You cannot add yourself to a group you are already a part of.";

            return _repository.AddUserToGroup(name, email, user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public Record AddRecord(string name, string type, decimal amount, string description, string groupName)
        {
            var group = _repository.GetGroup(groupName);
            if (Constants.Constants.ConstantsDictionary.ContainsKey(type) && group != null)
            {
                Constants.Constants.ConstantsDictionary.TryGetValue(type, out var typeNumber);
                Record record = new Record(typeNumber, name, description, amount);
                
                if (typeNumber < 3)
                {
                    record.Amount = Math.Abs(record.Amount);
                }
                else
                {
                    record.Amount = Math.Abs(record.Amount) * -1.0m;
                }

                return !_repository.AddGroupRecord(record, group) ? null : record;
            }
            return null;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<bool> RemoveRecord(string id)
        {
            Guid key = new Guid(id);
            var item = _repository.GetRecord(key);
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var groups = _repository.GetGroups(user);
            foreach (var group in groups)
            {
                if (group.GroupNavigation.Records.Contains(item))
                {
                    _repository.RemoveRecord(key);
                    return true;
                }
            }
            return false;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public Record EditRecord(string id, string name, string type, decimal amount, string description, string groupName)
        {
            var group = _repository.GetGroup(groupName);
            if (Constants.Constants.ConstantsDictionary.ContainsKey(type))
            {
                Constants.Constants.ConstantsDictionary.TryGetValue(type, out var typeNumber);
                if (typeNumber < 3)
                {
                    return _repository.EditRecordGroup(new Guid(id), name, typeNumber, Math.Abs(amount), description, group);
                }
                return _repository.EditRecordGroup(new Guid(id), name, typeNumber, Math.Abs(amount) * -1, description, group);
            }
            return null;
        }

        [HttpGet]
        public async Task<string> GetConfig(DateTime dateFrom, DateTime dateTo, string transactionType,
                                            string transactionSubtype, string groupName, string xAxis)
        {
            List<Record> records = new List<Record>();
            if (groupName != null)
            {
                if (groupName.Equals("All Groups"))
                {
                    var user = await _userManager.GetUserAsync(HttpContext.User);
                    var groups = _repository.GetGroups(user);
                    foreach (var group in groups)
                    {
                        records.AddRange(group.GroupNavigation.Records);
                    }
                }
                else
                {
                    var group = _repository.GetGroup(groupName);
                    records = group.Records;
                }
            }
            else
            {
                var user = await _userManager.GetUserAsync(HttpContext.User);
                records = _repository.GetRecords(user);
            }

            if (dateFrom != DateTime.MinValue && dateTo != DateTime.MinValue)
            {
                records = records.Where(t => t.Date.Date >= dateFrom.Date && t.Date.Date <= dateTo.Date).ToList();
            }

            if (transactionType.Equals("expenses"))
            {
                records = records.Where(t => t.Amount < decimal.Zero).ToList();
                if (transactionSubtype != null)
                {
                    if (!transactionSubtype.Equals("allTypes"))
                    {
                        Constants.Constants.ConstantsDictionary.TryGetValue(transactionSubtype, out var typeNumber);
                        records = records.Where(t => t.Type == typeNumber).ToList();
                    }

                }
            }
            else if (transactionType.Equals("incomes"))
            {
                records = records.Where(t => t.Amount >= decimal.Zero).ToList();
                if (transactionSubtype != null)
                {
                    if (!transactionSubtype.Equals("allTypes"))
                    {
                        Constants.Constants.ConstantsDictionary.TryGetValue(transactionSubtype, out var typeNumber);
                        records = records.Where(t => t.Type == typeNumber).ToList();
                    }
                }
            }

            //If there is no records matching the conditions, return nothing
            if (records.Count == 0) return "";

            List<decimal> amounts = new List<decimal>();
            string[] labels = GetLabels(dateFrom, dateTo, amounts, records, xAxis);


            return JsonConvert.SerializeObject(new { amounts, labels });
        }

        private string[] GetLabels(DateTime dateFrom, DateTime dateTo, List<decimal> amounts, List<Record> records, string xAxis)
        {
            if (xAxis.Equals("Category"))
            {
                HashSet<string> categories = new HashSet<string>();
                Dictionary<int, decimal> sums = new Dictionary<int, decimal>();
                foreach (var record in records)
                {
                    categories.Add(record.Type < 3
                        ? ((IncomeType) record.Type).ToString()
                        : ((ExpenseType) record.Type).ToString());
                    if (sums.ContainsKey(record.Type))
                    {
                        sums.TryGetValue(record.Type, out var sum);
                        sums.Remove(record.Type);
                        sums.Add(record.Type, sum + record.Amount);
                    }
                    else
                    {
                        sums.Add(record.Type, record.Amount);
                    }
                }

                foreach (var sum in sums.Values)
                {
                    amounts.Add(sum);
                }
                return categories.ToArray();
            }
            if (dateTo == DateTime.MinValue && dateFrom == DateTime.MinValue)
            {
                dateTo = DateTime.MinValue;
                dateFrom = DateTime.MaxValue;
                foreach (var record in records)
                {
                    if (record.Date < dateFrom)
                    {
                        dateFrom = record.Date;
                    }

                    if (record.Date > dateTo)
                    {
                        dateTo = record.Date;
                    }
                }
            }
            if (dateTo > dateFrom.AddYears(1))
            {
                //years

Budgetco/Controllers/MyRecordsController.cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading.Tasks;
using Budgetco.Constants;
using Budgetco.Data;
using Newtonsoft.Json;
using Budgetco.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Budgetco.Controllers
{
    [Authorize]
    public class MyRecordsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IBudgetRepository _repository;

        public MyRecordsController(UserManager<ApplicationUser> userManager, IBudgetRepository repository)
        {
            _userManager = userManager;
            _repository = repository;
        }

        public async Task<IActionResult> Index()
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            
            var inputModel = new InputModel
            {
                RecordModel = _repository.GetRecords(user)
            };
            foreach (var record in inputModel.RecordModel)
            {
                inputModel.PartialModel.Add(record, null);
            }
            return View(inputModel);
        }

        public IActionResult About()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<Record> AddRecord(string name, string type, decimal amount, string description)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (Constants.Constants.ConstantsDictionary.ContainsKey(type) && user != null)
            {
                Constants.Constants.ConstantsDictionary.TryGetValue(type, out var typeNumber);
                Record record = new Record(typeNumber, name, description, amount);
                if (typeNumber < 3)
                {
                    record.Amount = Math.Abs(record.Amount);
                }
                else
                {
                    record.Amount = Math.Abs(record.Amount)*-1.0m;
                }

                if (!_repository.AddRecord(record, user))
                {
                    return null;
                }
                return record;
            }
            return null;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<bool> RemoveRecord(string id)
        {
            Guid key = new Guid(id);
            var user = await _userManager.GetUserAsync(HttpContext.User);
            user.Records = _repository.GetRecords(user);
            if (user.Records.Exists(t => t.Id.Equals(key)))
            {
                _repository.RemoveRecord(key);
                return true;
            }
            else return false;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public Record EditRecord(string id, string name, string type, decimal amount, string description)
        {
            if (Constants.Constants.ConstantsDictionary.ContainsKey(type))
            {
                Constants.Constants.ConstantsDictionary.TryGetValue(type, out var typeNumber);
                if (typeNumber < 3)
                {
                    return _repository.EditRecord(new Guid(id), name, typeNumber, Math.Abs(amount), description);
                }
                return _repository.EditRecord(new Guid(id), name, typeNumber, Math.Abs(amount)*-1, description);
            }
            return null;
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<int> HasDatabaseSetChanged(int records, bool groupView)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            if (groupView)
            {
                var count = 0;
                var groups = _repository.GetGroups(user);
                foreach (var group in groups)
                {
                    foreach (var record in group.GroupNavigation.Records)
                    {
                        count++;
                    }
                }

                return count;
            }
            else
            {
                return _repository.GetRecordsCount(user);
            }
        }

    }
}

Budgetco/Views/Shared/RecordsView.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Constants
@model Dictionary<Record, UserGroup>
<table class="table" id="records-table">
    <thead>
    <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Description</th>
        <th>Amount</th>
        <th>Date</th>
       
            @if (Model.Values.Any(t => t != null))
            {
                <th>Group</th>
            }
        <th></th>
    </tr>
    </thead>
    <tbody>
    @if (Model != null)
    {
        foreach (var item in Model.Keys)
        {
            
            if (@item.Amount >= decimal.Zero)
            {
                <tr value="@(item.Id)" class="income-record">
                    
                    <td>@(item.Name)</td>
                    <td>@((IncomeType) item.Type)</td>
                    <td>@(item.Description)</td>
                    <td>@(item.Amount)</td>
                    <td>@item.Date.ToString("dd.MM.yyyy")</td>
                    @{
                        Model.TryGetValue(item, out var group);
                        if (group != null)
                        {
                            <td value="@(group.GroupNavigation.Name)">@(group.GroupNavigation.Name)</td>
                        }
                    }
                    <td>
                        <a class="edit-item" style="cursor: pointer;">Edit</a> |
                        <a class="remove-item" style="cursor: pointer;">Remove</a>
                    </td>
                    
                </tr>
            }
            else
            {
                <tr value="@(item.Id)" class="expense-record">
                    <td>@(item.Name)</td>
                    <td>@((ExpenseType) item.Type)</td>
                    <td>@(item.Description)</td>
                    <td>@(item.Amount)</td>
                    <td>@item.Date.ToString("dd.MM.yyyy")</td>
                    @{
                        Model.TryGetValue(item, out var group);
                        if (group != null)
                        {
                            <td value="@(group.GroupNavigation.Name)">@(group.GroupNavigation.Name)</td>
                        }
                    }
                    <td>
                        <a class="edit-item" style="cursor: pointer;">Edit</a> |
                        <a class="remove-item" style="cursor: pointer;">Remove</a>
                    </td>
                    
                </tr>
            }
        }
    }
    </tbody>
</table>

Budgetco/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Budgetco</title>
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/jquery-ui-1.12.1.custom/jquery-ui.css" rel="stylesheet" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/ju/dt-1.10.16/sc-1.4.4/datatables.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
    <style>
        nav a:hover {
            color: #a8b3c4 !important;
            font-weight: bold;
        }
        nav a {
            color: whitesmoke !important;
            font-weight: bold;
        }
        nav button {
            text-decoration: none;
            color: whitesmoke;
        }
    </style>
</head>
<body>
    
    <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color: #006fe0;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-action="Index" asp-controller="MyRecords" class="navbar-brand" style="color: whitesmoke">Budgetco</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Groups" asp-action="Index" >Groups</a></li>
                    <li><a asp-controller="MyRecords" asp-action="About" >About</a></li>
                    <li><a asp-controller="MyRecords" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Budgetco</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/v/ju/dt-1.10.16/sc-1.4.4/datatables.min.js"></script>
        <script src="~/lib/chart.js/dist/Chart.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js" type="text/javascript"></script>
        <script src="//cdn.datatables.net/plug-ins/1.10.16/sorting/datetime-moment.js" type="text/javascript"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
<!-- used for ajax in AddAntiForgeryToken() -->
<form id="__AjaxAntiForgeryForm" action="#" method="post">@Html.AntiForgeryToken()</form>
</body>

</html>